### ISSUE TITLE
Do not require `version` to be provided when submitting to px-wp-insights-server

### ISSUE THREAD

**Issue by westonruter** [rtCamp/px-wp-insights#186]
See https://github.com/ampproject/amp-wp/pull/6718#issuecomment-985793701:

> I'm still getting an error when submitting this, but this time it seems to be an issue with the insights server. It's responding with:
> 
> ```json
> {
>     "status": "fail",
>     "data": [
>         {
>             "message": "required validation failed on plugins.0.version",
>             "field": "plugins.0.version",
>             "validation": "required"
>         },
>         {
>             "message": "required validation failed on plugins.5.version",
>             "field": "plugins.5.version",
>             "validation": "required"
>         },
>         {
>             "message": "required validation failed on plugins.6.version",
>             "field": "plugins.6.version",
>             "validation": "required"
>         }
>     ]
> }
> ```
> 
> It is because I have active plugins which do not have a `version`. This should not be a required field.

**Comment by dhaval-parekh** [comment]
The extension (plugin/theme) version can not be empty since the error source is directly linked with the extension version and not to the extension itself. And that may lead to an issue while processing support requests when the process will not able to generate `extension_version_slug` for `extension_versions` and `error_sources` which is the primary key for `extension_versions`.

One possible solution is to allow an empty version for plugin and theme in a support request but fill it with empty version `0.0` while processing the request.

**Comment by westonruter** [comment]
Yes, `0.0` as default makes sense.
